FROM debian:buster
LABEL maintainer "Cheewai Lai <clai@csir.co.za>"

ARG GOSU_VERSION=1.11
ARG GOSU_DOWNLOAD_URL="https://github.com/tianon/gosu/releases/download/${GOSU_VERSION}/gosu-amd64"
ARG S6_OVERLAY_VERSION=v1.22.1.0
ARG DEBIAN_FRONTEND=noninteractive
ARG DOCKERIZE_VERSION=v0.6.1
ARG http_proxy
ARG https_proxy

# For sklearn.cluster: python-numpy libatlas-dev libatlas3gf-base
# For scipy: liblapack3gf liblapack-dev gfortran
# For Python script to interact with Postgis database: python-psycopg2 libgeos-3.4.2 libgeos-dev
# For geolookup: python-simplejson
RUN apt-get update \
 && apt-get -y upgrade \
 && apt-get install -y curl wget unzip build-essential \
    python3 python3-dev python3-setuptools python3-pip \
    librabbitmq4 \
    python3-psycopg2 \
    python3-numpy \
    python3-pyproj \
    python3-scipy \
    python3-sklearn \
    python3-shapely \
    python3-rtree \
    python3-pytest \
    gdal-bin python3-gdal \
 && curl -o gosu -kfsSL "$GOSU_DOWNLOAD_URL" \
 && mv gosu /usr/bin/gosu \
 && chmod +x /usr/bin/gosu \
 && curl -k -fsSL https://github.com/just-containers/s6-overlay/releases/download/${S6_OVERLAY_VERSION}/s6-overlay-amd64.tar.gz | tar xfz - -C / \
 && curl -k -fsSL https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz | tar xfz - -C /usr/bin \
 && pip3 install geopy>=1.10.0 \
 && pip3 install pika \
 && pip3 install kombu \
 && pip3 install python-daemon \
 && pip3 install reverse_geocoder \
 && pip3 install python-logstash \
 && pip3 install PyYAML \
 && pip3 install rethinkdb \
 && pip3 install dateutils \
 && pip3 install blinker raven --upgrade \
 && pip3 install redis rq \
 && apt-get -y autoremove \
 && apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# pip install librabbitmq fails
# https://github.com/celery/librabbitmq/issues/118#issuecomment-393181309

ADD docker-entrypoint.sh /docker-entrypoint.sh
ENTRYPOINT ["/docker-entrypoint.sh"]
